name: uoc
channels:
- pytorch
- defaults
dependencies:
- python=3.8.1
- pytorch=1.4.0
- torchvision=0.5.0
- cudatoolkit=10.1
- numpy=1.18.1
- scipy=1.4.1
- pandas=1.0.1
- imageio=2.6.1
- h5py=2.10.0
- tensorboard=2.1.0
- seaborn=0.10.1
- jupyter==1.0.0
